### ISSUE TITLE
Basically impossible to download the releases

### ISSUE THREAD

**Issue by animeking9901** [axonasif/gearlock#11]
Forced registration and on top of that you have to PRAY a admin allows it,which in the world of dynamic IPs being tainted (especially cellular) is not a good policy for downloading. Would consider changing this before someone decides to mirror your hard work instead,as bugmenot already has logins for your forums as well

**Comment by axonasif** [comment]
> PRAY a admin allows it

What do you mean by this? Guess you're using some sort of illegal email -- which are blocked by our anti-spam system, nothing to do about that, that's your problem.

>  Would consider changing this before someone decides to mirror your hard work instead,as bugmenot already has logins for your forums as well.

Hahaha, guess you didn't search enough yet? There are already a big number of people mirroring stuff from our community forum in places like youtube, web and even worse: _looped adlinks_.
But you know what? **I DON'T CARE**

The main intention of our forum is to connect people together who are related with android-x86 stuff.
If that doesn't sound good enough to you then stay out of it and that's all right. Not an issue honestly, it's just your personal choice.

Have a good day.

**Comment by hmtheboy154** [comment]
Maybe next time we let them Download without account.... if that's what they want.

**Comment by hmtheboy154** [comment]
But idk why people said "impossible"

**Comment by axonasif** [comment]
> Maybe next time we let them Download without account.... if that's what they want.

I've plans to auto publish the installation binaries directly in github once after I'm done with new GDK --- which is meant to handle stuff(package/extension source code) at https://github.com/gearlock-users-repo

**Comment by animeking9901** [comment]
my point was that locking a prog behind registration is bullshit quite frankly,and being a total high and mighty PRICK was unncessary
