### ISSUE TITLE
Cannot update gearlock use gearlock itself in China

### ISSUE THREAD

**Issue by nukemiko** [axonasif/gearlock#12]
While I entered to gearlock, it remained me: "New update found, do you want to perform update?"
I selected "Yes", then gearlock structed: "Checking if you are connect to internet by pinging google".
Obviously, I can't connect to Google directly in China. I tried to use some "anti-blockade" network toolkits such as v2ray and ShadowsocksR, even I edit the /system/etc/hosts, but they are still useless.

I guess, your way of checking internet connection is simliar to "ping google.com". But China blocked all connections to Google, v2ray and ShadowsocksR not work on ping. So gearlock judged "no internet connection", because of "failed to ping google".

**Comment by axonasif** [comment]
You can access gitlab, right?

**Comment by axonasif** [comment]
https://github.com/axonasif/gearlock/commit/880cbfe674ff493c739638281e78155d987cb958 fixes your issue hopefully.
Now you may manually update gearlock in the offline way by following this guide:
https://wiki.supreme-gamers.com/gearlock/user-guide/installation-and-updating

**Comment by SGNight** [comment]
> [880cbfe](https://github.com/axonasif/gearlock/commit/880cbfe674ff493c739638281e78155d987cb958) fixes your issue hopefully.
> Now you may manually update gearlock in the offline way by following this guide:
> https://wiki.supreme-gamers.com/gearlock/user-guide/installation-and-updating
> 
> And afterwards in the future you shouldn't face issues with auto-updating.

i think we can host our website server as secondary download link.
if user fail to ping gitlab than after 10 seconds it'll ping to a secondary host that can be our web server.

and about vpn we still needs to double check on it's security since some people in past have reported IP was leaking only few vpn can work properly without exposing your real ip.

**Comment by axonasif** [comment]
> > [880cbfe](https://github.com/axonasif/gearlock/commit/880cbfe674ff493c739638281e78155d987cb958) fixes your issue hopefully.
> > Now you may manually update gearlock in the offline way by following this guide:
> > https://wiki.supreme-gamers.com/gearlock/user-guide/installation-and-updating
> > And afterwards in the future you shouldn't face issues with auto-updating.
> 
> i think we can host our website server as secondary download link.
> if user fail to ping gitlab than after 10 seconds it'll ping to a secondary host that can be our web server.
> 
> and about vpn we still needs to double check on it's security since some people in past have reported IP was leaking only few vpn can work properly without exposing your real ip.

Yeah, that can be done, I was just being lazy :laughing: 
Adding to todo.
