### ISSUE TITLE
Use pipe instead of file

### ISSUE THREAD

**Issue by riadkabir45** [axonasif/gearlock#18]
in bashbox syntax check
Instead of throwing the functionized script into file and source to check for error
you can pipe the functionized script to bash to get exact same result
but u wont have to deal with /tmp or $RANDOM for this case

i have tasted and it works

**Comment by axonasif** [comment]
How is this an issue/problem/error for the **end-user**?

**Comment by axonasif** [comment]
And FYI, tmp file will get created even if you pipe it and I'm manually handing this behavior as I prefer to have control over this.

**Comment by riadkabir45** [comment]
Salute

**Comment by axonasif** [comment]
> Salute

I'm not amused, thank you 😁
