### ISSUE TITLE
Is Gearlock can worked on a emulator like bluestacks

### ISSUE THREAD

**Issue by mazhe1988** [axonasif/gearlock#21]
As say in the title

**Comment by axonasif** [comment]
Running inside an windows android emulator should be possible but no plans for this in the near future.

**Comment by Xtr126** [comment]
It's possible to install gearlock by patching ramdisk but it won't be reliable.
Emulator updates and gearlock updates will likely break gearlock. Installing kernel and mesa is also not good as default kernel. BlueStacks has built-in button to switch between arm and x86 so unity fix won't be helpful.
