### ISSUE TITLE
Can't get the files of gearlock

### ISSUE THREAD

**Issue by Rezin247** [axonasif/gearlock#42]
tried running "primeOS-classic_0.6.1-20211206.iso" via "Advanced_Android-x86_Installer_v1.6_Full.exe" and everything is fine but it cant get the files for gearlock... is there a solution?
![image](https://github.com/axonasif/gearlock/assets/140264820/989e019c-a84b-4cb2-968a-869c96e8b197)
![image](https://github.com/axonasif/gearlock/assets/140264820/b7fabc39-49c2-4bad-96ce-d9ff48eebbf5)

**Comment by axonasif** [comment]
Don't install gearlock through it. The links are broken now. Install gearlock separately after primeos is done.
